#!/usr/bin/env python3
"""Build the merged Arabic idiom knowledge base.

Produces ``data/idioms/ar/idioms_merged_llm_formatted.jsonl`` with the same shape
as the Chinese KB (``data/idioms/zh/idioms_merged_llm_formatted.jsonl``) plus an
``examples`` field::

    {"idiom": ..., "index": N,
     "output": {"idiom", "entities", "literal_meanings",
                "figurative_meanings", "examples"},
     "meta":   {"sources", "varieties", "source_refs"}}

Any field with no valid value is written as the string ``"NAN"``.

INCLUSION CRITERIA (enforced in code, not by convention)
--------------------------------------------------------
1. **Human-authored only.** The idiom *and* its meaning explanations must be
   written by humans, not generated by an AI. Sources that fail this are listed in
   :data:`EXCLUDED_SOURCES` with the reason, and are never fetched.
2. **At least one meaning.** A row is dropped unless it has a non-empty
   ``figurative_meanings`` *or* ``literal_meanings``.

Per-field provenance is recorded so a partially-machine-assisted field can be
audited later (see ``FIELD_PROVENANCE`` and the ``--drop-llm-assisted`` flag).

Deduplication uses :func:`culture.data_processing.ar_idioms.normalize.normalize_ar`
so that vocalized and unvocalized spellings of the same proverb collapse together —
without it, the same proverb appears several times across sources.

Usage::

    python -m culture.data_processing.ar_idioms.build_ar_idioms \\
        --out data/idioms/ar/idioms_merged_llm_formatted.jsonl

    python -m culture.data_processing.ar_idioms.build_ar_idioms --self-test
"""

import argparse
import csv
import json
import logging
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from culture.data_processing.ar_idioms.normalize import (  # noqa: E402
    looks_arabic,
    normalize_ar,
    strip_quote_furniture,
)

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("culture.ar_idioms.build")

NAN = "NAN"

# A single-token "idiom" is a dictionary lemma, not an expression.
MIN_IDIOM_TOKENS = 2


# --------------------------------------------------------------------------- #
# Sources that FAIL criterion 1 — never fetched. Documented so the decision is
# auditable rather than silently implicit.
# --------------------------------------------------------------------------- #
EXCLUDED_SOURCES = {
    "tahaalselwii/arabic-proverbs-collection#popular_arabic_proverbs.csv":
        "575 rows, AI-generated; the dataset card itself warns entries 'may contain "
        "inaccuracies… or statements that are not commonly recognized as authentic "
        "Arabic proverbs'.",
    "aymansharara/IdiomX":
        "Idioms are ENGLISH; the Arabic layer is GPT-translated glosses. Verified: "
        "example_language=='en' for 100% of rows, is_generated_example True for all.",
    "kenantang/IdiomTranslate30":
        "East-Asian idioms; Arabic is a Gemini-generated target translation only.",
    "ArSyra/*":
        "Gated + commercially sold; only a 50-row preview is on HF and it is not "
        "actually accessible.",
}


# --------------------------------------------------------------------------- #
# Source registry
# --------------------------------------------------------------------------- #
@dataclass
class SourceSpec:
    """One upstream dataset and how to turn its rows into KB records."""
    name: str
    hf_id: str
    adapter: Callable[[Dict[str, Any]], Optional[Dict[str, Any]]]
    files: Optional[List[str]] = None      # data_files for load_dataset
    split: str = "train"
    variety: str = NAN                     # default dialect label
    provenance: Dict[str, str] = field(default_factory=dict)
    note: str = ""


# --------------------------------------------------------------------------- #
# Source-text cleaning — defects found by the entry-by-entry LLM audit
# --------------------------------------------------------------------------- #
# Shamela printed-page markers, e.g. ⦗٢٣٨⦘ — 535 entries (5.0%), all from the
# al-Maydani classical file. They appear both inside glosses and inside headwords.
_RE_PAGE_MARKER = re.compile(r"⦗[^⦘]{0,12}⦘")
# Bidi controls (LRM/RLM/embedding) — 332 entries (3.1%), almost all Tunisian.
_RE_BIDI = re.compile(r"[‎‏‪-‮⁦-⁩]")
# HTML scrape residue: hard newlines + long indentation runs — 5,488 entries
# (51.7%), the single largest mechanical defect. Present in both idiom strings
# (splitting them across lines) and glosses.
_RE_WS = re.compile(r"\s+")
# A trailing footnote numeral left by the scrape, e.g. "...يقلعه ١٩" or "»٨٩".
_RE_TRAILING_FOOTNOTE = re.compile(r"\s*[»«]?\s*[٠-٩\d]{1,3}\s*$")
# Glosses that state no meaning at all.
_RE_NO_MEANING = re.compile(
    r"^\s*(?:معناه\s+ظاهر|المعنى\s+ظاهر|معناها\s+ظاهر)\s*[.。]?\s*$"
)
_RE_CROSSREF_ONLY = re.compile(r"^\s*(?:انظر|راجع|وانظر)\s*[:：]")
# Verbs/markers that introduce an actual gloss. If a cross-reference also carries
# one of these, it is stating a meaning as well as pointing elsewhere — keep it.
_RE_HAS_GLOSS = re.compile(r"يضرب|يقال|كناية|معناه|معناها|المراد|يريدون|أي\s")


def clean_source_text(s: str, *, strip_footnote: bool = False) -> str:
    """Remove scrape artefacts from one source string.

    All of these were found by auditing the built KB entry by entry; each is a
    deterministic, content-preserving removal (nothing meaningful is dropped).
    """
    if not s:
        return ""
    s = _RE_PAGE_MARKER.sub(" ", s)
    s = _RE_BIDI.sub("", s)
    s = _RE_WS.sub(" ", s).strip()
    if strip_footnote:
        s = _RE_TRAILING_FOOTNOTE.sub("", s).strip()
    return s


# al-Maydani lists a head proverb and then its variant forms inline, in quotes:
#   أَضَلُّ مِنْ ضَبٍّ، و"مِنْ وَرَلٍ"و"مِنْ وَلَدِ الْيَرْبُوعِ"
# and sometimes an editorial citation:  ...اليقِينُ(انظر الفاخر ١.٢)قال هشام
# Left in the `idiom` field this is not merely untidy — the surface never occurs
# in running text, so the corpus matcher scores ZERO recall on those entries.
# Split the head off and keep the variants in `meta.idiom_variants` (lossless).
# NB the waw may carry a diacritic (وَ"...") and the variant may be introduced by a
# guillemet instead of a quote. Requiring a bare `و"` missed 7 of the 16 cases.
_HARAKAT = r"[ً-ْٰ]*"
_RE_VARIANT_TAIL = re.compile(
    rf"[،,؛;]\s*و{_HARAKAT}\s*(?=[\"«“])"      # ...، و"variant"   /   ...، وَ"variant"
    rf"|\s*،?\s*ويقال{_HARAKAT}\s*(?=[\"«“])"  # ...، ويقال"variant"
    rf"|\s+(?=«)"                              # ...المثل « variant
)
_RE_EDITORIAL = re.compile(r"\s*\((?:انظر|راجع)[^)]*\)\s*.*$")
# A lone quote left dangling at an EDGE, either after the head is split off or
# present in the source (…وَالجَمَلْ مَا شَالهُمْ"). It breaks corpus matching.
# Edges only, deliberately: an INTERIOR quote is doing word-separation work in
# these scraped entries, and deleting it glues words together — stripping every
# quote turned وأظنه"إنا into وأظنهإنا and معه"مِنْ"نحو into معهمِنْنحو.
_RE_STRAY_QUOTE = re.compile(r"^[\"«»“”„‟']+|[\"«»“”„‟']+$")


def split_variant_furniture(idiom: str) -> tuple:
    """``idiom`` -> (head_idiom, [variant strings]). No-op when there is no tail."""
    if not idiom:
        return "", []
    s = _RE_EDITORIAL.sub("", idiom).strip()
    m = _RE_VARIANT_TAIL.search(s)
    if not m:
        # No variant tail, but a dangling quote may still be present.
        return _RE_STRAY_QUOTE.sub("", s).strip(" ،,؛;"), []
    head, tail = s[:m.start()].strip(" ،,؛;"), s[m.start():]
    variants = [v.strip() for v in re.findall(r"[\"«“]([^\"»”]+)[\"»”]?", tail) if v.strip()]
    head = _RE_STRAY_QUOTE.sub("", head).strip(" ،,؛;")
    return (head or s), variants


def is_contentless_meaning(s: str) -> bool:
    """True for glosses that assert no meaning (fails inclusion criterion 2).

    Two attested patterns: ``معناه ظاهر`` ("its meaning is obvious", 13 entries)
    and a bare cross-reference ``انظر: «...»`` (142 entries) that defers to
    another headword without stating anything.
    """
    s = (s or "").strip()
    if not s:
        return True
    if _RE_NO_MEANING.match(s):
        return True
    # A cross-reference is contentless only if it merely points elsewhere. If it
    # ALSO carries a gloss marker (يضرب / يقال / كناية / معناه / أي), it states a
    # meaning too and is kept. This is more principled than a length cutoff.
    return bool(_RE_CROSSREF_ONLY.match(s)) and not _RE_HAS_GLOSS.search(s)


def _clean(v: Any) -> str:
    """Coerce a cell to a stripped string; '', None, 'nan' -> ''."""
    if v is None:
        return ""
    s = clean_source_text(str(v))
    return "" if s.lower() in {"", "nan", "none", "null"} else s


def _as_list(v: Any) -> List[str]:
    """Wrap a scalar/……list into a list of non-empty strings."""
    if v is None:
        return []
    if isinstance(v, (list, tuple)):
        out = [_clean(x) for x in v]
    else:
        out = [_clean(v)]
    return [x for x in out if x]


# ---- adapters (one per upstream schema) ----------------------------------- #
def _ad_tahaalselwii(row):
    """`Arabic Proverb`, `Explanation` (Arabic prose)."""
    idiom = _clean(row.get("Arabic Proverb") or row.get("Arabic-Proverb"))
    expl = _clean(row.get("Explanation"))
    if not idiom:
        return None
    return {"idiom": idiom, "figurative_meanings": _as_list(expl)}


def _ad_jawaher(row):
    """`Proverbs`, `Ar_Explanation`, `En_Explanation`, `En_Equivalent`, `Variety`."""
    idiom = _clean(row.get("Proverbs"))
    if not idiom:
        return None
    # Jawaher's English is HUMAN (verified: 710/1017 unique equivalents, max reuse
    # 8x, genuine idiomatic matches like "Blood is thicker than water"). Keep it,
    # but in its own field — mixing English into figurative_meanings polluted an
    # Arabic-only field and the audit flagged it on every Jawaher entry.
    return {"idiom": idiom,
            "figurative_meanings": _as_list(row.get("Ar_Explanation")),
            "figurative_meanings_en": (_as_list(row.get("En_Explanation"))
                                       + _as_list(row.get("En_Equivalent"))),
            "variety": _clean(row.get("Variety")) or NAN}


def _ad_kinayat(row):
    """`Idiom`, `Ar_Explanation`, `full_sentence` (only 150/325 rows have a sentence).

    ``Incorrect_Explanation`` is a deliberate distractor and is NEVER ingested.
    """
    idiom = _clean(row.get("Idiom"))
    if not idiom:
        return None
    return {"idiom": idiom,
            "figurative_meanings": _as_list(row.get("Ar_Explanation")),
            "examples": _as_list(row.get("full_sentence")),
            "variety": "EGY"}


def _ad_tunisian(row):
    """`tunisan_proverb`, `proverb_arabic_explaination`, `dynamic` (En equivalent).

    ``caption_formal``/``prompt``/``dynamic`` are machine-translated noise, dropped.
    """
    idiom = _clean(row.get("tunisan_proverb"))
    if not idiom:
        return None
    # `dynamic` is DROPPED: the audit showed it is machine-produced boilerplate —
    # "no good deed goes unpunished" recycled across 9 unrelated proverbs, plus
    # literal-MT nonsense ("the genie and the genie", "from a sugar cane") and one
    # degenerate repetition loop. That fails inclusion criterion 1.
    return {"idiom": idiom,
            "figurative_meanings": _as_list(row.get("proverb_arabic_explaination")),
            "variety": "TUN"}


def _ad_absher(row):
    """`Term`, `Meaning_of_term`, `Dialect type`. Rows repeat across 6 MCQ files.

    Absher is a crowd-sourced dialect GLOSSARY, not an idiom list: the audit found
    12-14 of every ~20 sampled entries were bare lemmas (خندريس، مطانيج، زين، فقع)
    with one-word definitions. We keep only multi-word entries, which is the
    strongest signal available without per-entry judgement.
    """
    idiom = _clean(row.get("Term"))
    if not idiom or len(idiom.split()) < MIN_IDIOM_TOKENS:
        return None
    return {"idiom": idiom,
            "figurative_meanings": _as_list(row.get("Meaning_of_term")),
            "variety": f"SAU/{_clean(row.get('Dialect type')) or 'General'}"}


def _ad_hassaniya(row):
    """Alpaca format: `input` = proverb, `output` = meaning."""
    idiom = _clean(row.get("input"))
    if not idiom:
        return None
    return {"idiom": idiom, "figurative_meanings": _as_list(row.get("output")),
            "variety": "MAU"}


SOURCES: List[SourceSpec] = [
    SourceSpec(
        name="tahaalselwii_classical", hf_id="tahaalselwii/arabic-proverbs-collection",
        files=["classical_arabic_proverbs.csv"], adapter=_ad_tahaalselwii,
        variety="Classical/MSA",
        provenance={"idiom": "human", "figurative_meanings": "human"},
        note="Digitized from مجمع الأمثال (al-Maydani, d. 1124).",
    ),
    SourceSpec(
        name="tahaalselwii_colloquial", hf_id="tahaalselwii/arabic-proverbs-collection",
        files=["colloquial_arabic_proverbs.csv"], adapter=_ad_tahaalselwii,
        variety="EGY",
        provenance={"idiom": "human", "figurative_meanings": "human"},
        note="Digitized from الأمثال العامية (Ahmad Taymur Pasha, 1949).",
    ),
    SourceSpec(
        name="jawaher", hf_id="UBC-NLP/Jawaher-benchmark",
        files=["Jawaher_train_fixed.jsonl", "Jawaher_test.jsonl"], adapter=_ad_jawaher,
        provenance={"idiom": "human", "figurative_meanings": "human"},
        note="NAACL 2025. Use *_fixed* (the stale Jawaher_train.jsonl lacks Variety). "
             "Paper has 10,037 proverbs; only 1,017 are public. NO LICENSE DECLARED.",
    ),
    SourceSpec(
        name="kinayat", hf_id="menaattia/Kinayat",
        files=["Arabic_Idioms - Kinayat_test.csv"], adapter=_ad_kinayat,
        variety="EGY",
        provenance={"idiom": "human", "figurative_meanings": "human",
                    "examples": "llm_generated_human_reviewed"},
        note="Mined from الكنايات العامية (Taymur, 1949). Usage sentences are "
             "GPT-4.1-generated then human-reviewed (51.3% edited).",
    ),
    SourceSpec(
        name="tunisian", hf_id="HabibaAbderrahim/Tunisian-Proverbs-with-Image-"
                               "Associations-A-Cultural-and-Linguistic-Dataset",
        files=["dataset.csv"], adapter=_ad_tunisian, variety="TUN",
        provenance={"idiom": "human", "figurative_meanings": "human"},
        note="MT columns (caption_formal/prompt) deliberately dropped.",
    ),
    SourceSpec(
        name="absher", hf_id="Renad10/Absher-Benchmark",
        files=["Proverbs/Proverbs_Meaning_questions.csv",
               "Phrases/Phrases_Meaning_questions.csv"],
        adapter=_ad_absher, variety="SAU",
        provenance={"idiom": "human", "figurative_meanings": "human"},
        note="Scraped from the Moajam crowd dictionary (human-written, crowd-sourced "
             "rather than expert-edited). The same terms repeat across six MCQ task "
             "files; we read only the *_Meaning_questions.csv pair.",
    ),
    SourceSpec(
        name="hassaniya", hf_id="ahmed02mk/amthal-hassaniya",
        files=["amthal_hassaniya.jsonl"], adapter=_ad_hassaniya, variety="MAU",
        provenance={"idiom": "human", "figurative_meanings": "human"},
        note="From موسوعة الأمثال الحسانية (بكار ولد احمدو).",
    ),
]


# --------------------------------------------------------------------------- #
# Arabic variety labelling
# --------------------------------------------------------------------------- #
# Unlike the Chinese/English KBs, Arabic entries carry an explicit variety label:
# "Arabic" spans a classical literary register and a dozen mutually-divergent
# spoken varieties, and an idiom is usually valid in exactly one of them.
#
# Each raw source label maps to (ISO 639-3 code, region name, register).
#   * `code` uses the same ISO 639-3 inventory as GlotCC / FineWeb-2
#     (arb/arz/ary/aeb/arq/apc/ajp/acm/afb/ars/acw/apd/mey/...), so the labels
#     line up with the corpora we will filter.
#   * `code` is NAN where no confident ISO assignment exists — a guessed code is
#     worse than an honest gap. The region name is always populated.
#   * `register` is kept SEPARATE from variety: the sources conflate them
#     ("Classical/MSA"), but they are orthogonal, and the morphology study found
#     register predicts how frozen an expression is (classical amthal 73.9%
#     surface-identical vs kinayat 67.6%) — which decides how we match it.
VARIETY_MAP: Dict[str, tuple] = {
    # register-bearing labels
    "Classical/MSA":  ("arb", "Classical Arabic",           "classical"),
    "MSA":            ("arb", "Modern Standard Arabic",     "msa"),
    # North Africa
    "EGY":            ("arz", "Egyptian",                   "colloquial"),
    "TUN":            ("aeb", "Tunisian",                   "colloquial"),
    "ALG":            ("arq", "Algerian",                   "colloquial"),
    "MOR":            ("ary", "Moroccan (Darija)",          "colloquial"),
    "LIB":            ("ayl", "Libyan",                     "colloquial"),
    "MAU":            ("mey", "Hassaniyya (Mauritanian)",   "colloquial"),
    "SUD":            ("apd", "Sudanese",                   "colloquial"),
    # Levant
    "SYR":            ("apc", "North Levantine (Syrian)",   "colloquial"),
    "LEB":            ("apc", "North Levantine (Lebanese)", "colloquial"),
    "PAL":            ("ajp", "South Levantine (Palestinian)", "colloquial"),
    "JOR":            ("ajp", "South Levantine (Jordanian)",   "colloquial"),
    # Mesopotamia + Gulf
    "IRQ":            ("acm", "Mesopotamian (Iraqi)",       "colloquial"),
    "UAE":            ("afb", "Gulf (Emirati)",             "colloquial"),
    "QAT":            ("afb", "Gulf (Qatari)",              "colloquial"),
    "KUW":            ("afb", "Gulf (Kuwaiti)",             "colloquial"),
    "BAH":            ("afb", "Gulf (Bahraini)",            "colloquial"),
    "OMA":            ("acx", "Omani",                      "colloquial"),
    "YEM":            ("ayn", "Yemeni (Sanaani)",           "colloquial"),
    # Saudi regions (Absher). Only Najdi/Hijazi/Eastern have a confident code.
    "SAU/Central":    ("ars", "Najdi (Central Saudi)",      "colloquial"),
    "SAU/Western":    ("acw", "Hijazi (Western Saudi)",     "colloquial"),
    "SAU/Eastern":    ("afb", "Gulf (Eastern Saudi)",       "colloquial"),
    "SAU/Southern":   (NAN,   "Southern Saudi",             "colloquial"),
    "SAU/Northern":   (NAN,   "Northern Saudi",             "colloquial"),
    "SAU/General":    (NAN,   "Saudi (unspecified)",        "colloquial"),
    "SAU":            (NAN,   "Saudi (unspecified)",        "colloquial"),
}

# Which register wins when one idiom is attested in several sources.
_REGISTER_RANK = {"classical": 3, "msa": 2, "colloquial": 1}


def resolve_varieties(raw_labels: List[str]) -> Dict[str, Any]:
    """Map raw source labels to ISO codes / region names / a single register."""
    codes, regions, registers, unknown = [], [], [], []
    for lab in raw_labels:
        hit = VARIETY_MAP.get(lab)
        if hit is None:
            unknown.append(lab)
            continue
        code, region, reg = hit
        if code != NAN and code not in codes:
            codes.append(code)
        if region not in regions:
            regions.append(region)
        registers.append(reg)
    register = max(registers, key=lambda r: _REGISTER_RANK.get(r, 0)) if registers else NAN
    return {"variety": codes or NAN, "variety_region": regions or NAN,
            "register": register, "unknown_labels": unknown}


# --------------------------------------------------------------------------- #
# Record assembly
# --------------------------------------------------------------------------- #
FIELDS = ["entities", "literal_meanings", "figurative_meanings",
          "figurative_meanings_en", "examples"]


def make_record(parsed: Dict[str, Any], spec: SourceSpec) -> Optional[Dict[str, Any]]:
    """Normalize one adapter output into the KB record shape, or None if invalid."""
    # Strip the quote furniture dictionaries wrap around headwords BEFORE storing:
    # every one of the 3,187 Taymur colloquial proverbs is «...», and those
    # characters never occur around the proverb in running text.
    idiom = _clean(parsed.get("idiom"))
    # Trailing scrape footnote (e.g. «...»٨٩) then wrapping quote furniture.
    idiom = strip_quote_furniture(clean_source_text(idiom, strip_footnote=True))
    # al-Maydani appends variant forms in quotes after the head proverb. Keeping
    # them in `idiom` makes the surface unmatchable in running text (zero corpus
    # recall for those entries), so split them off and preserve them separately.
    idiom, idiom_variants = split_variant_furniture(idiom)
    if not idiom or not looks_arabic(idiom):
        return None
    if len(idiom.split()) < MIN_IDIOM_TOKENS:
        return None

    # Drop glosses that state no meaning ("معناه ظاهر", bare "انظر: ...").
    fig = [m for m in _as_list(parsed.get("figurative_meanings"))
           if not is_contentless_meaning(m)]
    lit = [m for m in _as_list(parsed.get("literal_meanings"))
           if not is_contentless_meaning(m)]
    rec = {
        "idiom": idiom,
        "entities": _as_list(parsed.get("entities")),
        "literal_meanings": lit,
        "figurative_meanings": fig,
        "figurative_meanings_en": _as_list(parsed.get("figurative_meanings_en")),
        "examples": _as_list(parsed.get("examples")),
        "_variety": parsed.get("variety") or spec.variety,
        "_source": spec.name,
        "_idiom_variants": idiom_variants,
    }
    # Criterion 2: at least one meaning.
    if not rec["literal_meanings"] and not rec["figurative_meanings"]:
        return None
    return rec


def merge_records(records: Iterable[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Merge across sources, keyed on the NORMALIZED idiom form.

    Same proverb, different vocalization/orthography → one entry whose field lists
    are the de-duplicated union, with provenance accumulated in ``meta``.
    """
    merged: Dict[str, Dict[str, Any]] = {}
    for rec in records:
        key = normalize_ar(rec["idiom"])
        if not key:
            continue
        cur = merged.get(key)
        if cur is None:
            merged[key] = {
                "idiom": rec["idiom"],
                **{f: list(rec[f]) for f in FIELDS},
                "_varieties": [rec["_variety"]] if rec["_variety"] != NAN else [],
                "_sources": [rec["_source"]],
            }
            continue
        # Prefer the longer surface form as canonical (usually the vocalized one,
        # which carries more information for display/tagging).
        if len(rec["idiom"]) > len(cur["idiom"]):
            cur["idiom"] = rec["idiom"]
        for f in FIELDS:
            for v in rec[f]:
                if v not in cur[f]:
                    cur[f].append(v)
        if rec["_variety"] != NAN and rec["_variety"] not in cur["_varieties"]:
            cur["_varieties"].append(rec["_variety"])
        if rec["_source"] not in cur["_sources"]:
            cur["_sources"].append(rec["_source"])
    return list(merged.values())


def to_output_record(m: Dict[str, Any], index: int) -> Dict[str, Any]:
    """Final on-disk shape, mirroring the Chinese KB. Empty fields become ``"NAN"``.

    Arabic additionally carries ``variety``/``variety_region``/``register`` inside
    ``output`` — a deliberate divergence from the zh/en schema, because an Arabic
    idiom belongs to a specific variety in a way a chengyu does not.
    """
    v = resolve_varieties(m["_varieties"])
    out = {"idiom": m["idiom"]}
    for f in FIELDS:
        out[f] = m[f] if m[f] else NAN
    out["variety"] = v["variety"]
    out["variety_region"] = v["variety_region"]
    out["register"] = v["register"]
    meta = {
        "sources": m["_sources"],
        "varieties_raw": m["_varieties"] or NAN,   # source labels, for traceability
    }
    if v["unknown_labels"]:
        meta["unmapped_variety_labels"] = v["unknown_labels"]
    return {"idiom": m["idiom"], "index": index, "output": out, "meta": meta}


# --------------------------------------------------------------------------- #
# Loading
# --------------------------------------------------------------------------- #
def _parse_file(path: str) -> List[Dict[str, Any]]:
    """Parse one downloaded data file by extension."""
    ext = os.path.splitext(path)[1].lower()
    if ext == ".jsonl":
        with open(path, encoding="utf-8") as f:
            return [json.loads(l) for l in f if l.strip()]
    if ext == ".json":
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, list) else data.get("data", [])
    if ext in (".csv", ".tsv"):
        # utf-8-SIG, not utf-8: the tahaalselwii CSVs carry a UTF-8 BOM, which
        # otherwise lands inside the first column name ('﻿Arabic Proverb')
        # and silently made every adapter lookup miss — all 7,730 rows dropped.
        with open(path, encoding="utf-8-sig", newline="") as f:
            return list(csv.DictReader(f, delimiter="\t" if ext == ".tsv" else ","))
    raise ValueError(f"Unsupported data file extension: {path}")


def load_source(spec: SourceSpec, cache_dir: Optional[str] = None) -> List[Dict[str, Any]]:
    """Fetch a source by downloading its data files directly from the Hub.

    Deliberately NOT ``datasets.load_dataset``. Three of these repos break it:

    * ``Tunisian-Proverbs-…`` ships **5,189 PNGs and a ``dataset.py`` loading
      script**, so ``load_dataset`` stalls resolving the whole repo — we only
      want the one 999-row CSV.
    * ``Jawaher-benchmark`` declares train/test splits in its card, so passing
      custom ``data_files`` raises ``ExpectedMoreSplitsError: {'test'}``.
    * ``Absher-Benchmark`` stores the same terms across six MCQ task files.

    Pulling named files with ``hf_hub_download`` sidesteps all of it, is
    reproducible, and drops the heavyweight ``datasets`` dependency.
    """
    from huggingface_hub import hf_hub_download

    if not spec.files:
        raise ValueError(f"{spec.name}: `files` must be listed explicitly")
    rows: List[Dict[str, Any]] = []
    for fname in spec.files:
        path = hf_hub_download(spec.hf_id, fname, repo_type="dataset",
                               cache_dir=cache_dir)
        got = _parse_file(path)
        logger.info("  %s <- %s (%d rows)", spec.name, fname, len(got))
        rows.extend(got)
    return rows


def build(specs: List[SourceSpec], cache_dir: Optional[str] = None,
          drop_llm_assisted: bool = False) -> tuple:
    """Fetch + adapt + filter every source. Returns (records, per-source report)."""
    records: List[Dict[str, Any]] = []
    report: List[Dict[str, Any]] = []
    for spec in specs:
        try:
            rows = load_source(spec, cache_dir)
        except Exception as e:  # noqa: BLE001 — one bad source must not kill the build
            logger.error("FAILED to load %s (%s): %s", spec.name, spec.hf_id, e)
            report.append({"source": spec.name, "status": "FAILED", "error": str(e)})
            continue

        kept = dropped_no_meaning = dropped_bad = 0
        for row in rows:
            parsed = spec.adapter(row)
            if parsed is None:
                dropped_bad += 1
                continue
            if drop_llm_assisted:
                for f, prov in spec.provenance.items():
                    if prov != "human" and f in parsed:
                        parsed[f] = []
            rec = make_record(parsed, spec)
            if rec is None:
                dropped_no_meaning += 1
                continue
            records.append(rec)
            kept += 1

        logger.info("%-24s rows=%-7d kept=%-7d dropped(no meaning/invalid)=%d/%d",
                    spec.name, len(rows), kept, dropped_no_meaning, dropped_bad)
        report.append({"source": spec.name, "hf_id": spec.hf_id, "status": "ok",
                       "rows": len(rows), "kept": kept,
                       "dropped_no_meaning": dropped_no_meaning,
                       "dropped_invalid": dropped_bad, "note": spec.note})
    return records, report


def coverage(out_records: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Field-coverage stats for the final KB."""
    n = len(out_records)
    stats = {"total": n}
    for f in FIELDS:
        have = sum(1 for r in out_records if r["output"][f] != NAN)
        stats[f] = {"have": have, "nan": n - have,
                    "pct": round(100.0 * have / n, 2) if n else 0.0}
    return stats


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--out", default="data/idioms/ar/idioms_merged_llm_formatted.jsonl")
    p.add_argument("--report", default=None, help="Write the build report JSON here.")
    p.add_argument("--sources", default=None,
                   help="Comma-separated subset of source names (default: all).")
    p.add_argument("--cache_dir", default=None)
    p.add_argument("--drop-llm-assisted", action="store_true",
                   help="Blank any field whose provenance is not 'human' (strictest "
                        "reading of criterion 1; drops Kinayat's usage sentences).")
    p.add_argument("--self-test", action="store_true",
                   help="Run offline adapter/merge tests on fixtures; no network.")
    return p


def main() -> int:
    args = build_parser().parse_args()
    if args.self_test:
        return self_test()

    specs = SOURCES
    if args.sources:
        want = {s.strip() for s in args.sources.split(",") if s.strip()}
        unknown = want - {s.name for s in SOURCES}
        if unknown:
            raise SystemExit(f"Unknown sources: {sorted(unknown)}")
        specs = [s for s in SOURCES if s.name in want]

    logger.info("Excluded by criterion 1 (AI-generated / not Arabic idioms):")
    for k, v in EXCLUDED_SOURCES.items():
        logger.info("  - %s: %s", k, v)

    records, report = build(specs, args.cache_dir, args.drop_llm_assisted)

    # Fail loudly rather than silently shipping an empty/partial KB.
    failed = [r for r in report if r.get("status") == "FAILED"]
    if not records:
        for r in failed:
            logger.error("  %s -> %s", r["source"], r.get("error"))
        raise SystemExit(
            f"ABORT: no records loaded ({len(failed)}/{len(report)} sources failed). "
            "Is `datasets` installed and is the network reachable?"
        )
    if failed:
        logger.warning("%d/%d sources FAILED to load — the KB below is INCOMPLETE: %s",
                       len(failed), len(report), [r["source"] for r in failed])

    merged = merge_records(records)
    out_records = [to_output_record(m, i) for i, m in enumerate(merged)]

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        for r in out_records:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    stats = coverage(out_records)
    logger.info("Wrote %d unique idioms to %s (from %d raw records; %d merged away)",
                len(out_records), out_path, len(records), len(records) - len(out_records))
    logger.info("Field coverage: %s", json.dumps(stats, ensure_ascii=False))

    if args.report:
        Path(args.report).parent.mkdir(parents=True, exist_ok=True)
        with open(args.report, "w", encoding="utf-8") as f:
            json.dump({"sources": report, "coverage": stats,
                       "excluded": EXCLUDED_SOURCES}, f, ensure_ascii=False, indent=2)
        logger.info("Wrote report to %s", args.report)

    print(json.dumps(stats, ensure_ascii=False, indent=2))
    return 0


# --------------------------------------------------------------------------- #
# Offline self-test
# --------------------------------------------------------------------------- #
def self_test() -> int:
    """Exercise every adapter + the criteria + dedup on fixtures. No network."""
    spec_by_name = {s.name: s for s in SOURCES}

    # --- adapters ---------------------------------------------------------- #
    r = _ad_tahaalselwii({"Arabic Proverb": "أهل مكة أدرى بشعابها",
                          "Explanation": "يضرب لمن هو أعلم بشأنه"})
    assert r["idiom"] == "أهل مكة أدرى بشعابها" and len(r["figurative_meanings"]) == 1

    r = _ad_jawaher({"Proverbs": " إنك لا تجني من الشوك العنب",
                     "Ar_Explanation": "يضرب لمن يصنع المعروف في غير أهله",
                     "En_Explanation": "Doing good to the wrong people.",
                     "En_Equivalent": "You can't make a silk purse out of a sow's ear.",
                     "Variety": "MSA"})
    # English now lives in its OWN field; the Arabic field stays Arabic-only.
    assert r["variety"] == "MSA"
    assert r["figurative_meanings"] == ["يضرب لمن يصنع المعروف في غير أهله"]
    assert len(r["figurative_meanings_en"]) == 2
    assert "English equivalent" not in json.dumps(r, ensure_ascii=False)

    r = _ad_kinayat({"Idiom": "خَبَرَ أبْيَضْ", "Ar_Explanation": "كناية عن الخبر السيئ",
                     "Incorrect_Explanation": "DISTRACTOR — must not appear",
                     "full_sentence": "يا خَبَرَ أبْيَضْ! ايه اللي هو عمله ده."})
    assert r["examples"] == ["يا خَبَرَ أبْيَضْ! ايه اللي هو عمله ده."]
    assert "DISTRACTOR" not in json.dumps(r, ensure_ascii=False)   # never ingested

    r = _ad_kinayat({"Idiom": "أَجْرِ مْنَاوِلْ", "Ar_Explanation": "معناه كذا",
                     "full_sentence": ""})          # 175/325 rows have no sentence
    assert r["examples"] == []

    r = _ad_tunisian({"tunisan_proverb": "إذا تقول البلوط أحلى من التمر",
                      "proverb_arabic_explaination": "يقصد به المداهن",
                      "caption_formal": "MT GARBAGE", "dynamic": "people always talk"})
    # BOTH machine columns dropped: caption_formal AND dynamic (recycled boilerplate).
    assert "MT GARBAGE" not in json.dumps(r, ensure_ascii=False)
    assert "people always talk" not in json.dumps(r, ensure_ascii=False)
    assert r["figurative_meanings"] == ["يقصد به المداهن"]

    r = _ad_absher({"Term": "إذا حجت البقرة على قرونها",
                    "Meaning_of_term": "بمعنى المستحيل", "Dialect type": "General"})
    assert r["variety"] == "SAU/General"
    # Absher is a dialect glossary: bare lemmas are rejected outright.
    assert _ad_absher({"Term": "خندريس", "Meaning_of_term": "نوع من التمر"}) is None
    assert _ad_absher({"Term": "زين", "Meaning_of_term": "جميل"}) is None

    r = _ad_hassaniya({"input": "ألْبَلْ تبرك على أكبارها",
                       "output": "يضرب لأهمية الكبار في مجتمعهم"})
    assert r["variety"] == "MAU"

    # --- scrape-artefact cleaning (found by the entry-by-entry LLM audit) ---- #
    assert clean_source_text("قال ⦗٢٣٨⦘ الشيء") == "قال الشيء"        # page marker
    assert clean_source_text("\u200fمثل عربي") == "مثل عربي"            # RLM
    assert clean_source_text("مثل\n                   عربي") == "مثل عربي"  # HTML
    assert clean_source_text("يقلعه ١٩", strip_footnote=True) == "يقلعه"
    assert clean_source_text("") == ""

    # contentless glosses (criterion 2)
    assert is_contentless_meaning("معناه ظاهر")
    assert is_contentless_meaning("المعنى ظاهر.")
    assert is_contentless_meaning("انظر: «الجعان يحلم بسوق العيش»")
    assert not is_contentless_meaning("يضرب لمن هو أعلم بشأن نفسه")
    # a cross-reference WITH real content is kept
    assert not is_contentless_meaning(
        "انظر: كذا. ويضرب هذا المثل لمن يصنع المعروف في غير أهله ولا يجد جزاء")

    # a row whose only gloss is contentless is dropped by criterion 2
    s_cl = spec_by_name["tahaalselwii_colloquial"]
    assert make_record({"idiom": "مثل عربي هنا",
                        "figurative_meanings": ["معناه ظاهر"]}, s_cl) is None
    # single-token headwords are rejected everywhere
    assert make_record({"idiom": "زين", "figurative_meanings": ["جميل"]}, s_cl) is None

    # --- REGRESSION: guillemets stripped from the stored surface form ------- #
    s_col = spec_by_name["tahaalselwii_colloquial"]
    r = _ad_tahaalselwii({"Arabic Proverb": "«آخِرِ الحَيَاة الْمُوتْ»",
                          "Explanation": "حكمة جرت مجرى الأمثال"})
    rec = make_record(r, s_col)
    assert rec["idiom"] == "آخِرِ الحَيَاة الْمُوتْ", rec["idiom"]
    assert "«" not in rec["idiom"] and "»" not in rec["idiom"]

    # --- criterion 2: a row with no meaning is dropped --------------------- #
    s = spec_by_name["tahaalselwii_classical"]
    assert make_record({"idiom": "مثل بلا شرح", "figurative_meanings": []}, s) is None
    assert make_record({"idiom": "مثل عربي", "literal_meanings": ["شرح حرفي"]}, s) is not None
    # non-Arabic junk rejected
    assert make_record({"idiom": "hello world", "figurative_meanings": ["xyz"]}, s) is None

    # --- dedup across sources via normalization ---------------------------- #
    recs = [
        make_record({"idiom": "إنَّ دَوَاءَ الشَّقِّ أنْ تَحُوصَهُ",       # vocalized
                     "figurative_meanings": ["شرح كلاسيكي"]}, s),
        make_record({"idiom": "ان دواء الشق ان تحوصه",                  # bare
                     "figurative_meanings": ["شرح آخر"]},
                    spec_by_name["jawaher"]),
    ]
    merged = merge_records(recs)
    assert len(merged) == 1, f"expected dedup to 1, got {len(merged)}"
    assert merged[0]["idiom"] == "إنَّ دَوَاءَ الشَّقِّ أنْ تَحُوصَهُ"      # longer form kept
    assert len(merged[0]["figurative_meanings"]) == 2                    # union
    assert set(merged[0]["_sources"]) == {"tahaalselwii_classical", "jawaher"}

    # --- output shape + NAN filling ---------------------------------------- #
    out = to_output_record(merged[0], 0)
    assert set(out["output"]) == {"idiom", *FIELDS,
                                  "variety", "variety_region", "register"}
    assert out["output"]["entities"] == NAN          # nothing supplies entities
    assert out["output"]["examples"] == NAN
    assert out["output"]["figurative_meanings"] != NAN
    assert out["index"] == 0 and out["idiom"] == merged[0]["idiom"]

    # Chinese-KB parity: same top-level keys plus `examples`, variety, `meta`.
    zh_output_keys = {"idiom", "entities", "literal_meanings", "figurative_meanings"}
    assert zh_output_keys <= set(out["output"])

    # --- Arabic variety labelling ------------------------------------------ #
    v = resolve_varieties(["EGY"])
    assert v == {"variety": ["arz"], "variety_region": ["Egyptian"],
                 "register": "colloquial", "unknown_labels": []}, v
    # register is separated from variety, and classical outranks colloquial
    assert resolve_varieties(["Classical/MSA"])["register"] == "classical"
    assert resolve_varieties(["Classical/MSA", "EGY"])["register"] == "classical"
    # Levantine countries collapse onto the right ISO codes
    assert resolve_varieties(["SYR", "LEB"])["variety"] == ["apc"]
    assert resolve_varieties(["PAL", "JOR"])["variety"] == ["ajp"]
    # Gulf states share afb; Oman does not
    assert resolve_varieties(["UAE", "QAT", "KUW", "BAH"])["variety"] == ["afb"]
    assert resolve_varieties(["OMA"])["variety"] == ["acx"]
    # No confident ISO code -> NAN, but the region is still recorded (no guessing)
    g = resolve_varieties(["SAU/General"])
    assert g["variety"] == NAN and g["variety_region"] == ["Saudi (unspecified)"]
    # Every label the sources actually emit must be mapped
    for lab in ["Classical/MSA", "MSA", "EGY", "TUN", "MAU", "SAU", "SAU/Central",
                "SAU/Western", "SAU/General", "SAU/Southern", "SAU/Northern",
                "SAU/Eastern", "UAE", "ALG", "SUD", "KUW", "PAL", "SYR", "YEM",
                "LIB", "QAT", "OMA", "JOR", "BAH", "IRQ", "MOR", "LEB"]:
        assert lab in VARIETY_MAP, f"unmapped source label: {lab}"

    # --- coverage stats ----------------------------------------------------- #
    st = coverage([out])
    assert st["total"] == 1 and st["figurative_meanings"]["have"] == 1
    assert st["examples"]["nan"] == 1

    # --- drop-llm-assisted blanks Kinayat examples -------------------------- #
    ks = spec_by_name["kinayat"]
    assert ks.provenance["examples"] == "llm_generated_human_reviewed"

    print("all build_ar_idioms.py self-tests passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
